### ISSUE TITLE
The current regex does not work with short format https://trello.com/c/aaaaaaaa Trello card URLs

### ISSUE THREAD

**Issue by ruohola** [delivered/attach-to-trello-card-action#12]
When sharing a card from Trello, the card URL will be in the form `https://trello.com/c/aaaaaaaa` (like is said [in the README](https://github.com/delivered/attach-to-trello-card-action/blame/master/README.md#L14)):

<img width="381" alt="image" src="https://user-images.githubusercontent.com/33625218/94905998-6e819380-04a6-11eb-82d9-1e29cffaff10.png">

The problem is that the current regex:

https://github.com/delivered/attach-to-trello-card-action/blob/a2cb319959d987ee3f8bb2d56bf0835560a27b72/index.js#L91

does not work at all with those kinds of links:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/33625218/94906451-2adb5980-04a7-11eb-8d3a-343c2079852f.png">

https://regex101.com/r/RSYl5m/1

**Comment by persononomo** [comment]
I tried to set up that behavior today. The same.
`no card urls in pr comment. nothing to do.`

**Comment by ruohola** [comment]
Yeah, a way to go around this is to not take the Trello card URL from the share sheet, but instead open the card and just press CMD+C, it will copy the full format link to the clipboard, which **does work** with the current regex:

<img width="307" alt="image" src="https://user-images.githubusercontent.com/33625218/94994682-de287900-05a1-11eb-91de-d59c670fae32.png">

**Comment by brianhenryhf** [comment]
@ruohola Ah, I see.  I'd tended to use the way you highlighted in https://github.com/delivered/attach-to-trello-card-action/issues/12#issuecomment-703116445, and didn't realize the miss b/w the README and impl.  Fixed in #13 .
