### ISSUE TITLE
Have more than one Trello link be detected

### ISSUE THREAD

**Issue by moisesrodriguez** [delivered/attach-to-trello-card-action#4]
In the previous issue you mention 

> The current implementation does require the link (https://trello.com/c/XYXYXYXYX/845-mycard-is-here) be the starting text on the first line of the PR body (it can be preceded with spaces on that line).

I'm finding this action very useful but it could be much better if

1) It would detect the Trello link no matter where the link is located. Not to be the starting text on the first line of the PR body
2) That it supports more than one Trello link

**Comment by brianhenryhf** [comment]
Near-term plans are to support >1 Trello link.  Should happen in the next few days.

At the moment, I'm trying to be very deliberate about which links result in attachments on cards, as the attachment has a specific meaning ("Trello card X is the feature request that caused PR Y"), and I don't want to accidentally add attachments for a casual reference to some other Trello card ("The feature this PR adds is a lot like https://trello.com/c/someotherfeature, but does blah blah differently").  So, near-term plans are not to add every link found (the Readme updates will illustrate the rules).  Longer-term, there could perhaps be a flag that changes behavior.  Could take a PR from a fork form an implementation to speed that up?

**Comment by brianhenryhf** [comment]
Released [v2.0.0](https://github.com/marketplace/actions/attach-to-trello-card?version=v2.0.0) to address >1 link part of this issue.  (The location part could be considered separately as its own issue.)

**Comment by moisesrodriguez** [comment]
I appreciate the work done on this!
